# Generated by Django 3.1.4 on 2021-02-10 08:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('convertors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='typemodel',
            name='urlss',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
