# Generated by Django 3.1.4 on 2021-02-10 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('convertors', '0002_typemodel_urlss'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typemodel',
            name='urlss',
        ),
        migrations.AddField(
            model_name='typemodel',
            name='urls',
            field=models.URLField(blank=True),
        ),
    ]
